import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

import Link from "next/link";

import Navbar from "../Components/MainComponents/Navbar";
import AboutBody from "../Components/MainComponents/AboutBody";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery([
    "example.hello",
    { text: "from tRPC" },
  ]);

  return (
    <>
      <Head>
        <title> Overwatch 2 API </title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
        <div className="MainBody">
          <Navbar />
          <AboutBody />
          <div> {data ? <p>{data.greeting}</p> : <p>Loading..</p>} </div>
          <div className="DocumentationHeader" >
            <Link href="/documentation">
              <h1> How to Use </h1>
            </Link>
          </div>

          <style>
            {`
            .DocumentationHeader:hover {
              text-shadow: 0 0 5px yellow;
              cursor: pointer;
            }
            .MainBody {
              background: linear-gradient(rgb(26, 109, 255) -0.42%, rgb(200, 34, 255) 100.42%);
              color: black;
            } 
            `}
          </style>
        </div>
    </>
  );
};

export default Home;
