import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

import Link from "next/link";

import Navbar from "../Components/MainComponents/Navbar";
import AboutBody from "../Components/MainComponents/AboutBody";

import styles from "../styles/Home.module.css"

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery([
    "example.hello",
    { text: "from tRPC" },
  ]);

  return (
    <>
      <Head>
        <title>Overwatch 2 API</title>
        <meta name="description" content="Generated by create-t3-app"/>
      </Head>

      <div className={styles.MainBody}>
        <Navbar />
        <AboutBody />
        <div className={styles.DocumentationHeader}>
          <Link href="/documentation">
              <h1 className={styles.headerFont}> How to Use </h1>
          </Link>
        </div>
      </div>
    </>
  );
};



export default Home;
