import { NextPage } from 'next'
import Head from 'next/head'


import Navbar from '../MainComponents/NavBar'
import Body from '../MainComponents/Body'
import Footer from '../MainComponents/Footer'

import styles from '../StylesMain/styles.module.css'


const App: NextPage = () => {
    return (
      <>
      <Head>
        <title>Fill A Role</title>
        <meta name="description" content="Generated by create-t3-app"/>
      </Head>

      <div className={styles.section}>
        <Navbar />
        <Body />
        <Footer />
      </div>
      </>
    )
}


//Color Scheme - 2C3531, 116466, #D4A59A, FFCB9A, D1E8E2
export default App
